name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ipl-streamlit-app:latest"
          echo "Building image: $IMAGE_REPO"
          docker build -t $IMAGE_REPO .

      - name: Push Docker image
        run: |
          IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ipl-streamlit-app:latest"
          echo "Pushing image: $IMAGE_REPO"
          docker push $IMAGE_REPO

      # (Optional) Run container with secret env at runtime (for test, not prod deployment)
      # - name: Run Docker container
      #   run: |
      #     IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ipl-streamlit-app:latest"
      #     docker run --rm -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} -p 8501:8501 $IMAGE_REPO

