name: Build and Push the Docker Image to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/ipl-streamlit-app:latest"
          echo "Building image: $IMAGE_REPO"
          docker build -t $IMAGE_REPO .

      - name: Push Docker image
        run: |
          IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/ipl-streamlit-app:latest"
          echo "Pushing image: $IMAGE_REPO"
          docker push $IMAGE_REPO